services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_HOST=db
    env_file:
      - .env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
  db:
    image: postgres:15
    container_name: db_container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  email:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
